# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    dir
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'
- script: |  
    dir
    ng build --prod
  displayName: 'npm build'
- script: |
    pwd
  displayName: 'test result'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './dist'
    ArtifactName: 'drop/dist'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './scripts'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './firebase.json'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    